### ISSUE TITLE
Call for v2 API improvements

### ISSUE THREAD

**Issue by devinivy** [hapipal/schmervice#12]
I currently find schmervice's API pretty good, and I can't think of any breaking changes that I'd like to make to it for v2.  But— what do you think?  Please feel free to broach discussions about any aspects of the API that you find limiting or otherwise suboptimal, and we can create additional issues as necessary to finalize discussions or flesh-out proposals.

If there are no issues then that would be great news— of course I don't want to encourage API changes just for fun, but now is a good time to make changes, so if something has been on your mind then let's talk about it!

**Comment by zemccartney** [comment]
Yo! 2 things have been kicking around my head as of late. Dunno if they'd actually constitute breaking changes, what work they'd even entail, or their general utility, just things I've reached for most recently i.e. recency bias in action 😛 

 #### Expose cached methods' cache interface more directly

Not sure what would go into this, but the first thing that came to mind was adding a `cache` property to each service method by which you could access server method's cache interface (`drop()` and `stats`)

So, given a `myService` with a method `verySlow`, for which caching is configured, you could do `myService.verySlow.cache.drop()` and `myService.verySlow.cache.stats`

Totally a minor inconvenience, given you can write out the full path to the method's cache

#### Provide some way for handling / classifying service errors

I'm a little foggy on what I'm thinking here still, apologies, but I think the crux is affording users more explicit control over their service methods' errors API. Really, boiling down to being able to selectively handle errors encountered in service methods and expose them as instances of service- or method-specific error classes, so any consumer, whether routing layer or exposed command or something else entirely, could check for the same errors that read as service-y (as opposed to checking for `Error`s or error classes from calls made within service methods), translate them to the output expected in their contexts e.g. `Boom` errors in the routing layer. I'd hope this would make error handling code more generic and readable, but also help keep service layers more generic, by avoiding leaking consumer-specific error outputs into service calls e.g. throwing `Boom` errors from within service methods (not that that's much of, if any, a problem in and of itself; sorry, this is sounding more and more like putting theory before practicality :) )

Preliminarily, I see 2 parts to this:

- an interface for describing rules by which service method errors are handled and translated into specific error classes; I imagine this could borrow from Bounce and Objection's createError methods e.g. https://vincit.github.io/objection.js/api/model/static-methods.html#static-createnotfounderror

- a way to expose relevant error classes, so they could be accessed via the currently available decorations e.g. `err instance of request.services().myService.ServiceError`

Still very much a half-baked idea, but I hope that gives enough of a gist. No idea if this would be actually useful! 
And I'm realizing something like this might not even belong in core, if the better route here would be to start life as a mixin, [again following Objection](https://vincit.github.io/objection.js/guide/plugins.html#plugin-development-best-practices). Haven't looked into that route at all, tho, but seems promising

**Comment by devinivy** [comment]
> Expose cached methods' cache interface more directly

Happy to report that this is already the case!  Cached methods _are_ server methods, so they should have the `serverMethod.cache` property with all that good stuff like `stats` and `drop()` on it.  Would happily accept a small addendum to the docs and/or tests to further solidify that.

> Provide some way for handling / classifying service errors

I could use a little help understanding exactly what the need is here, and I think more explicit code examples could be the path forward!  Can you show the code "you would want to write" with schmervice?  To get started I will provide an example which you can currently write, and I think checks most of the boxes you just mentioned, but if it leaves a gap maybe that's something useful to talk about.  The example I wrote sort of assumes haute-couture, so the first file is a service class that is registered to the server, and the second is a route that is registered to the same server.

```js
// lib/services/my-service.js

const { Service } = require('schmervice');

module.exports = class MyService extends Service {

    constructor() {

        this.ready = false;
    }

    async initialize() {

        await someStartupProcess();

        this.ready = true;
    }

    async performSomeAction() {

        if (!this.ready) {
            throw MyService.NotReadyError('MyService is not ready yet');
        }

        await performThatAction();
    }
};

// You could also do something slightly fancier here like use make-error
module.exports.NotReadyError = class NotReadyError extends Error {}
```

```js
// lib/route/my-route.js

const Boom = require('@hapi/boom');
const Bounce = require('@hapi/bounce');
const { NotReadyError } = require('../services/my-service');

module.exports = {
    method: 'post',
    path: '/perform-action',
    handler: async (request) => {

        const { myService } = request.services();

        try {
            await myService.performSomeAction();
        }
        catch (err) {
            // We also could have placed NotReadyError on the service instance within its constructor
            // then reference it as `myService.NotReadyError` it if that is preferred over require()ing it.
            Bounce.ignore(err, NotReadyError);
            throw Boom.serverUnavailable('Not ready yet!');
        }

        return { success: true };
    }
};
```

**Comment by zemccartney** [comment]
> Happy to report that this is already the case!

Ay! Sorry about that, not sure how I confused myself otherwise. Doi. Thanks!

> more explicit code examples could be the path forward! Can you show the code "you would want to write" with schmervice?

Ay, yea, sure thing. Sorry for the lack of clarity. Thanks a ton for writing up those examples! 🙏 🍻  Exactly what I was envisioning for the route. For the service, I was thinking of handling describing error handling in a static prop, like below, thinking of this prop similarly to the pal real world app's  `onPreResponse` extension for error handling, like a centralized error handler:


```js
// lib/services/my-service.js

const { Service } = require('schmervice');

module.exports = class MyService extends Service {

    constructor() {

        this.ready = false;
    }

    // This would rethrow system errors, wrapping all others in a `MyServiceError` Error class,
    // decorating with the object returned from the `decorate` func, comparable to the option of the 
    // same name in `new Boom.Boom`'s options
    static errors = {
        rethrow: 'system',
        decorate: (err) => {
            
            if (err instanceof Joi.ValidationError) {
                // could be any arbitrary props, whatever's useful for the application
                return {
                     cause: 'validation',
                     details: err.details
                } 
            } 

            return { cause: err };
        }
    }

    async initialize() {

        await someStartupProcess();

        this.ready = true;
    }

    async performSomeAction() {

        if (!this.ready) {
            throw new Error('MyService is not ready yet');
        }

        await performThatAction();
    }
};
```

But your example made me realize this approach makes it difficult / impossible to attribute a particular cause to a method error. If `performSomeAction` threw a plain `Error` if `this.ready` were falsey, the error decorator couldn't definitively say  such an error were due to `!this.ready` and were rethrowable as a `NotReady` subclass or otherwise decorated to describe that case. This static prop error handling approach seems better suited to handling third party errors e.g. raised by some tooling called within service methods, but really poorly suited for internal operational errors (by which I mean, errors we can anticipate within our own services that don't stem from third-party / library calls and aren't due to programmer goofers...is it clear I'm struggling w/ the words to say this 😝 ??). For those errors, it seems you want control over what errors you throw in methods themselves, in the context of the error, rather than later. 

ANYWAY, seems this thought is petering out. I'll go back to the drawing board, maybe revisit later, but the example you provided covers more than enough, super helpful 🙏  Thanks!
