### ISSUE TITLE
Pass parameters to service?

### ISSUE THREAD

**Issue by Birkbjo** [hapipal/schmervice#16]
Is there a way to pass parameters to the service? Either to the constructor or the `initialize`-method? The `options`-object is just options internal to `schmervice`, right? Is my use-case for passing some initialisation options off base and the intent is to set dependencies/options on the `context`-object? At least that's how I've solved passing options to the service.

In my opinion it would make sense to pass in an options-object to the `registerService(service, initOptions)` that would be passed to the `initialize()` and/or constructor.

**Comment by devinivy** [comment]
If you hand a function or class to `registerService()`, for convenience schmervice will construct the service using the arguments `(server, options)` where `options` are the current plugin's options.  However, you can also construct the service yourself with whatever arguments you like!

```js
const myService = new MyService(initOptions);
myService[Schmervice.name] = 'myService'; // You could also use Schmervice.withName()

server.registerService(myService);
```

Would this do the trick for you?

**Comment by Birkbjo** [comment]
Thanks for your quick reply! That should suffice!
