### ISSUE TITLE
Peer @hapi/hapi needs update

### ISSUE THREAD

**Issue by osukaa** [hapipal/schmervice#20]
Hello,

I was trying to update to hapi@21 today, and had an issue, noticed that schmervice peer dep range doesn't include 21

```json
{
   "peerDependencies": {
    "@hapi/hapi": ">=19 <21"
  }
}
```

**Comment by devinivy** [comment]
Will be getting out new versions with official support for hapi v21 soon!  In practice schmervice should not be affected by the breaking changes in v21 👍
