### ISSUE TITLE
Is there a way to stub a service for tests?

### ISSUE THREAD

**Issue by ekorolev** [hapipal/schmervice#8]
Hi!

I write integrational tests for my API server. Several services make requests to external servers like postgresql, redis etc. It's ok, but there is a service that makes requests to a server that I can't set up for each integrational test.

I tried to reinitialize the service like
```
server.registerService((server, options) => ({
  name: 'service_that_I_wanna_stub',
  stubbedMethod: () => {},
  anotherStubbedMethod: () => {}
});
```

But I got the error `A service named service_that_I_wanna_stub has already been registered.`

I have no idea how to solve my problem. Is there a way to make it work? Thank you.

**Comment by devinivy** [comment]
The main reason that this is not allowed is that we want to ensure multiple plugins aren't registering different services by the same name and creating a conflict.  I usually just stub the service methods directly in my tests:
```js
it('gets data from myService.', async (flags) => {
  const server = await getServer();
  const { myService } = server.services();

  const origMyMethod = myService.myMethod;
  myService.myMethod = () => ({
    stubbed: 'data'
  });

  flags.onCleanup = () => {
    myService.myMethod = origMyMethod;
  };

  // Do something that uses myService internally
});
```

If you would like to change this behavior of `server.registerService()` or `server.services()` for your purposes, hapi also provides a way to extend its behavior:

```js
server.decorate('server', 'services', myImplementation, {
  extend: true
});
```

In the future I would also be open to making it simpler to replace an entire service for testing purposes, as long as we don't have to compromise on preventing conflicts.  If you propose a way for this to work, I will happily consider it.

**Comment by devinivy** [comment]
With the release of v1.5.0's namespacing feature, stubbing is much simpler.  Say there's a service named `myService` registered in your plugin named `my-plugin`, and you would like to stub it out with `myMockService`:
```js
// This is how to access the original service instance
const { myService } = server.services('my-plugin');

// Mock out myService by mutating the object returned by server.services()
Object.assign(server.services('my-plugin'), {
    myService: myMockService
});

// Then when you're done, replace the original
Object.assign(server.services('my-plugin'), { myService });
```

The example above will also affect the services returned by `request.services()` and `h.services()` within `my-plugin` in the way you would probably desire/expect: `myService` will be stubbed-out in those contexts too.  Other plugins than `my-plugin` that have access to `myService` need to be stubbed out independently using the same technique.  Hope this helps!
