### ISSUE TITLE
Caching Objection.js SQL queries in server route

### ISSUE THREAD

**Issue by rickysullivan** [hapipal/schmervice#9]
Hi,

I'm trying to cache queries where data seldomly changes (also because the DB is dead slow and the response times to the server are shocking).

Relating to https://github.com/Vincit/objection.js/issues/980#issuecomment-400828235

Can you show an example of how you're using catbox to do this?

**Comment by devinivy** [comment]
Yeah, sure!  So the way this works is that you configure `caching` on your service to provide what is essentially a [server method](https://hapi.dev/api/?v=19.1.1#server.method()) configuration (which contains a [catbox policy](https://hapi.dev/api/?v=19.1.1#server.cache()) configuration) for the various methods on your service.

Say you have a service that looks like this, with a method involving a slow query:
```js
'use strict';

const { Service } = require('schmervice');

module.exports = class UserService extends Service {

    async count() {

        const { User } = this.server.models();

        // Suppose this query below is slow, i.e. if you have millions of users
        return await User.query().resultSize();
    }
};
```

You could implement caching by simply adding a caching config to the service:
```js
'use strict';

const { Service } = require('schmervice');

module.exports = class UserService extends Service {

    async count() {

        const { User } = this.server.models();

        // Suppose this query below is slow, i.e. if you have millions of users
        return await User.query().resultSize();
    }

    static get caching() {

        return {
            count: { // <-- the key is the method name
                expiresIn: 1000 * 60 * 15, // Results are good for 15minutes
                generateTimeout: 1000 * 60 // Bail on generation if it's taking over a minute
            }
        };
    }
};
```

And that's really all there is to it!  You can go very in-depth fine-tuning a caching configuration to have all sorts of different behaviors, particularly when combining the above with a stale timeout. Keep in mind if your method has non-simple arguments that you need to determine a cache key from the args manually by also configuring [`generateKey`](https://hapi.dev/api/?v=19.1.1#server.method()) in the caching config.  More docs: https://hapipal.com/docs/schmervice#servicecachingoptions.  An example in the hapipal.com codebase: https://github.com/hapipal/hapipal.com/blob/master/lib/services/github.js.

**Comment by rickysullivan** [comment]
NICE! Thanks for your help.

**Comment by rickysullivan** [comment]
I had an issue with request params (object) being passed to the function.

Fixed it by changing the cache key:

```
static get caching() {
    return {
      test: {
        cache: {
          expiresIn: 15 * 1000 * 60,
          generateTimeout: 1000 * 60
        },
        generateKey: params => {
          return JSON.stringify(params);
        }
      }
    };
  }
```

**Comment by rickysullivan** [comment]
Can you access the request from within a service method? Or do I need to pass it as a param?

**Comment by devinivy** [comment]
You can't access it in the service unless you pass it as a method argument.  I usually prefer to write my services to be HTTP-agnostic, so they only very rarely see an actual request object.

**Comment by rickysullivan** [comment]
Reworded: Related question. How can I found cache meta in the service? Like, how old the cache is etc. And, how can you specify caching when using functional style service?
